[PR] 모임 메인 - 정보 수정 화면 리팩토링
KUIT-CoNet/CoNet-iOS pull request #25
Opened 2024-01-03 13:41 UTC by ahhyun1015

## PR Type ⚙️
      
- [x] Refactor: 프로덕션 코드 리팩토링
- [x] Comment: 필요한 주석 추가 및 변경

<br>

## What is this PR? 📝

### Related Issue Number
- #11 
<br>

### Changes
- 텍스트 필드 클릭 시, 하단의 grayLiner과 textCountLabel 색상이 변경되는 부분이 누락돼서 추가했습니다.
- 초기 화면에서도 textCountLabel과 xButton이 표시되도록 수정했습니다.
- 텍스트 필드 레이아웃을 변경했습니다.
- 필요할 것 같은 주석은 추가했습니다.
- 버튼 컴포넌트(uploadButton) 이름을 변경했습니다.
<br>

## Other information 🔥
- 완료 버튼을 누르고 수정사항이 반영되기까지 약간의 딜레이가 발생하는데 이건 해결방안이 없을까용
- 코드를 깔끔하게 쓰려고 노력을 하긴하는데 혹시 코드가 복잡한가여...궁금합니다!
<br>

2024-01-04 16:12 UTC, slr-09 requested changes

2024-01-04 16:12 UTC, slr-09 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
> +        buttonClicks()
buttonClicks를 buttonActions로 바꿔주세용

2024-01-04 16:12 UTC, slr-09 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
> +        applyConstraintsToGathername()
gather 이라는 이름은 meeting으로 맞추는게 좋을 것 같아요! 
Refactor > Rename 기능으로 바꾸면 될 것 같습니당

2024-01-04 16:12 UTC, slr-09 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
>              make.trailing.equalTo(photoImageView.snp.trailing).offset(-147)
이건 방금 알아낸건데 leading과 trailing의 offset이 같은 경우에는 `make.horizontalEdges.equalTo(photoImageView.snp.horizontalEdges).inset(147)`와 같이 쓸 수 있습니다. 세로의 경우에는 verticalEdges로 쓸 수 있겠죠? 

추가로 이 컴포넌트는 가로 상으로 중앙에 위치하고 있으므로 값을 설정하지 않고 centerX를 사용하는 것도 좋을 것 같아요

2024-01-04 16:12 UTC, slr-09 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
모임 정보 수정 후 완료 버튼을 눌렀을 때, 버튼 클릭 액션이 잘 인식이 안되는 것 같아요 .. (api가 호출되지 않음)
+ 화면이 꺼지지 않습니다 
-> 이건 원인이 뭔지 차근차근 찾아봐야할 것 같네요 

추가로, 텍스트필드에 초점이 갔을 때 키보드가 올라오지 않는 것 같아용

2024-01-05 00:56 UTC, ahhyun1015 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
>              make.trailing.equalTo(photoImageView.snp.trailing).offset(-147)
오! 한번 적용해보겠습니다

2024-01-05 00:57 UTC, ahhyun1015 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
> +        applyConstraintsToGathername()
넵!

2024-01-05 01:55 UTC, ahhyun1015 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
완료 버튼을 누르면 한 5~8초 있다가 화면이 넘어가더라구요(api는 잘 작동되는것같은데...)

텍스트필드에 초점갔을 때 키보드가 안올라오는건 알아보니깐, 자동으로 맥 키보드로 감지되는 설정이 체크돼 있어서 그런거 였어요(첨 알게된 사실! 원래도 이랬었나요..흠) 사진처럼 설정하니깐 정상적으로 작동하네염
<img width="715" alt="스크린샷 2024-01-05 오전 10 50 19" src="https://github.com/KUIT-CoNet/CoNet-iOS/assets/121007805/10838679-a747-4539-afec-50fc3a507491">

2024-01-05 11:41 UTC, slr-09 approved these changes

2024-01-05 11:41 UTC, slr-09 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
제가 실행해봤을 때는 화면이 안넘어가요 ㅜㅜ 
그리고 버튼 인식이 안된다고 한건 무언가 너무 느린 것 같아요 뒤늦게 클릭이 마구 되는 느낌 .. 

layout 관련 코드만 모두 extension으로 넘긴 후 머지 해주세요! 
수고하셨습니당

2024-01-05 11:41 UTC, slr-09 commented on CoNet/Main/Meeting/MeetingInfoEditViewController.swift
현재 완료 버튼이 텍스트필드에 수정이 생기면 활성화가 되고 있는데, 수정 전 모임 이름과 같은 경우에는 다시 비활성화 되도록 추후에 수정하면 좋을 것 같아요!

2024-01-06 07:04 UTC, merged